lexik_jwt_authentication:
    token_extractors:
        authorization_header:
            enabled: true
            prefix:  Bearer
            name:    Authorization
        query_parameter:
            enabled: true
            name:    bearer
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
