#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# calc:
#   type:     rest
#   resource: App\Controller\CalculatorController

# Hello:
#   type:     rest
#   resource: App\Controller\HelloController